### ISSUE TITLE
Release date of the code

### ISSUE THREAD

**Issue by bing-stu** [pansanity666/TransHuman#1]
Hi, thanks for your contributions about human neural rendering. When would you like to release the code?

**Comment by pansanity666** [comment]
Hi, we are currently working on this. Code will be available in the next few days.

**Comment by bing-stu** [comment]
ok,thank you.


---- Replied Message ----
From  Xiao ***@***.***> Date  08/02/2023 12:37 To  ***@***.***> Cc  ***@***.***>***@***.***> Subject  Re: [pansanity666/TransHuman] Release date of the code (Issue #1)  

Hi, we are currently working on this. Code will be available in the next few days.
