### ISSUE TITLE
How to generate zju_depth_map_train?

### ISSUE THREAD

**Issue by Canon0521** [pansanity666/TransHuman#10]
I would like to know how zju_depth_map_train got it, can you give me the code to process or the zju_depth_map_train dataset？

**Comment by pansanity666** [comment]
Hi,

The code for rendering mesh contains depth_map outputs https://github.com/pansanity666/TransHuman/blob/efe870349f39e8e5fce3379b76107b0c4e35e2df/render_mesh_dynamic.py#L264

If you want SMPL depth map, you can change the NeRF mesh to SMPL mesh. 

Best,

**Comment by Canon0521** [comment]
> Hi,
> 
> The code for rendering mesh contains depth_map outputs
> 
> https://github.com/pansanity666/TransHuman/blob/efe870349f39e8e5fce3379b76107b0c4e35e2df/render_mesh_dynamic.py#L264
> 
> If you want SMPL depth map, you can change the NeRF mesh to SMPL mesh.
> 
> Best,

Thanks！
