### ISSUE TITLE
Bug in test

### ISSUE THREAD

**Issue by jintaiWang** [pansanity666/TransHuman#3]
Hi! We encounter a bug when we test on THuman Dataset.
It only occurs in extremely special circumstances.
https://github.com/pansanity666/TransHuman/blob/759b220410370f5ad322ecc68104414dd6401e29/lib/networks/cross_transformer.py#L298C28-L298C28
When alpha shape is [1, 1, 1], squeeze() will cause error. (It happen when density_mask only have one valid value)
We add unsqueeze() to avoid this bug and it work well.

**Comment by pansanity666** [comment]
Thanks for your report. I will fix it in the updated version.  Really an extreme case😃.
