### ISSUE TITLE
How to generate visibility maps?

### ISSUE THREAD

**Issue by wenbin-lin** [pansanity666/TransHuman#8]
Hi, thanks for your great work.
Can you share the code for generating visibility maps via rasterization, which [Neural_Human_Performer](https://github.com/YoungJoongUNC/Neural_Human_Performer) doesn't seem to provide either.

**Comment by pansanity666** [comment]
Hi, 

You can use the mesh renderer (e.g., pytorch3D) to render the SMPL mesh with the provided camera poses and get the depth map.  Then visibility maps can be achieved via depth map. 

Best,
