### ISSUE TITLE
how to obtain the freeviewpoint images?

### ISSUE THREAD

**Issue by liustu** [pansanity666/TransHuman#9]
Hi, the generated video is the views across frames with a fixed camera, while how to render the views in a freeviewpoint manner with a camera around the human? Thank you.

**Comment by pansanity666** [comment]
Hi, The provide script https://github.com/pansanity666/TransHuman?tab=readme-ov-file#free-viewpoint-video  should generate dynamic videos around the human. Pleaser refer the code  here https://github.com/pansanity666/TransHuman/blob/efe870349f39e8e5fce3379b76107b0c4e35e2df/lib/datasets/light_stage/can_smpl_perform.py#L69-L72
